# Automatically close questions and other uncategorized issues on inactivity
only: issues
daysUntilStale: 30
daysUntilClose: 7
exemptLabels:
  - bug
  - enhancement
exemptProjects: true
exemptMilestones: true
exemptAssignees: true
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: false
limitPerRun: 1
