language: node_js
notifications:
  email: false
before_install: npm config set progress=false && npm i -g npm@latest --no-audit
install: npm ci --no-audit
cache:
  directories:
  - node_modules
jobs:
  include:
  - node_js: lts/*
    script:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./scripts/check-pr.sh; fi
    - npm run all
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        cd $TRAVIS_BUILD_DIR/tests/allocators/arena && npm run build && cd .. && npm test arena &&
        cd $TRAVIS_BUILD_DIR/tests/allocators/buddy && npm run build && cd .. && npm test buddy &&
        cd $TRAVIS_BUILD_DIR/tests/allocators/tlsf  && npm run build && cd .. && npm test tlsf;
      fi
    env: Runs the tests on node.js LTS, also tests allocators
  - node_js: node
    script:
    - npm run all
    env: Runs the tests on node.js stable
  - node_js: node
    script:
    - npm run clean && npm run test:compiler
    env:
    - Runs experimental tests on node.js v8-canary using
    - ASC_FEATURES="simd,threads"
    - NVM_NODEJS_ORG_MIRROR="https://nodejs.org/download/v8-canary/"
