language: node_js
notifications:
  email: false
install:
  - yarn
stages:
- name: check-pr
  if: type = pull_request
env:
  global: JOBS=2
jobs:
  include:
  - stage: check-pr
    node_js: lts/*
    script: ./scripts/check-pr.sh
    env: Checks contributing guidelines before testing pull requests

  - stage: lint
    node_js: node
    script: yarn lint
    env: Checks the sources with TSLint

  - stage: test
    node_js: lts/*
    script: yarn clean && node bin/asc -v && yarn test
    env: Tests the sources on latest node.js LTS
  - node_js: lts/*
    script:
    - yarn clean
    - cd $TRAVIS_BUILD_DIR/tests/allocators/arena && yarn build && cd .. && yarn test arena
    - cd $TRAVIS_BUILD_DIR/tests/allocators/buddy && yarn build && cd .. && yarn test buddy
    - cd $TRAVIS_BUILD_DIR/tests/allocators/tlsf  && yarn build && cd .. && yarn test tlsf
    env: Tests the allocators on latest node.js LTS
  - node_js: node
    script: yarn clean && node bin/asc -v && yarn test
    env: Tests the sources on latest stable node.js

  - stage: build
    node_js: lts/*
    script: yarn build && node bin/asc -v && yarn test
    env: Builds and tests the bundle on latest node.js LTS
  - node_js: node
    script: yarn build && node bin/asc -v && yarn test
    env: Builds and tests the bundle on latest stable node.js

cache: yarn
