language: node_js
notifications:
  email: false
before_install: npm config set progress=false && npm i -g npm@latest --no-audit
install: npm ci --no-audit
jobs:
  include:
  - node_js: lts/*
    script:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" != "dev" ]; then ./scripts/check-pr.sh; fi
    - npm run all
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        cd $TRAVIS_BUILD_DIR/tests/allocators/rt-full && npm run build && cd .. && npm test rt-full &&
        cd $TRAVIS_BUILD_DIR/tests/allocators/rt-stub && npm run build && cd .. && npm test rt-stub;
      fi
    env: Runs the tests on node.js LTS, also tests allocators
  - node_js: node
    script:
    - npm run all
    env: Runs the tests on node.js stable
  - node_js: node
    script:
    - npm run clean && npm run test:compiler rt/flags threads
    env:
    - Runs experimental tests on node.js v8-canary using
    - ASC_FEATURES="mutable-globals,simd,threads,reference-types,bigint-integration"
    - NVM_NODEJS_ORG_MIRROR="https://nodejs.org/download/v8-canary/"
