language: node_js
notifications:
  email: false
stages:
  - name: check-pr
    if: type = pull_request
jobs:
  include:

  - stage: check-pr
    node_js: lts/*
    script: ./scripts/check-pr.sh
    env: Checks contributing guidelines before testing pull requests

  - stage: lint
    node_js: node
    script: npm run lint
    env: Checks the sources with TSLint

  - stage: test
    node_js: lts/*
    script: npm run clean && node bin/asc -v && npm test
    env: Tests the sources on latest node.js LTS
  - node_js: node
    env: Tests the sources on latest stable node.js

  - stage: build
    node_js: lts/*
    script: npm run build && node bin/asc -v && npm test
    env: Builds and tests the bundle on latest node.js LTS
  - node_js: node
    env: Builds and tests the bundle on latest stable node.js
