ASC_TARGET;
ASC_RUNTIME;
ASC_NO_ASSERT;
ASC_MEMORY_BASE;
ASC_OPTIMIZE_LEVEL;
ASC_SHRINK_LEVEL;

ASC_FEATURE_SIGN_EXTENSION;
ASC_FEATURE_MUTABLE_GLOBALS;
ASC_FEATURE_NONTRAPPING_F2I;
ASC_FEATURE_BULK_MEMORY;
ASC_FEATURE_SIMD;
ASC_FEATURE_THREADS;
ASC_FEATURE_EXCEPTION_HANDLING;
ASC_FEATURE_TAIL_CALLS;
ASC_FEATURE_REFERENCE_TYPES;
ASC_FEATURE_MULTI_VALUE;
ASC_FEATURE_GC;
ASC_FEATURE_MEMORY64;

// versions vary between builds
isDefined(ASC_VERSION_MAJOR);
isDefined(ASC_VERSION_MINOR);
isDefined(ASC_VERSION_PATCH);
