(module
 (type $i (func (result i32)))
 (type $v (func))
 (global $enum/Implicit.ZERO i32 (i32.const 0))
 (global $enum/Implicit.ONE i32 (i32.const 1))
 (global $enum/Implicit.TWO i32 (i32.const 2))
 (global $enum/Implicit.THREE i32 (i32.const 3))
 (global $enum/Explicit.ZERO i32 (i32.const 0))
 (global $enum/Explicit.ONE i32 (i32.const 1))
 (global $enum/Explicit.TWO i32 (i32.const 2))
 (global $enum/Explicit.THREE i32 (i32.const 3))
 (global $enum/Mixed.ZERO i32 (i32.const 0))
 (global $enum/Mixed.ONE i32 (i32.const 1))
 (global $enum/Mixed.THREE i32 (i32.const 3))
 (global $enum/Mixed.FOUR i32 (i32.const 4))
 (global $enum/NonConstant.ZERO (mut i32) (i32.const 0))
 (global $enum/NonConstant.ONE (mut i32) (i32.const 0))
 (global $enum/SelfReference.ZERO i32 (i32.const 0))
 (global $enum/SelfReference.ONE i32 (i32.const 1))
 (global $HEAP_BASE i32 (i32.const 4))
 (memory $0 1)
 (export "enum/Implicit.ZERO" (global $enum/Implicit.ZERO))
 (export "enum/Implicit.ONE" (global $enum/Implicit.ONE))
 (export "enum/Implicit.TWO" (global $enum/Implicit.TWO))
 (export "enum/Implicit.THREE" (global $enum/Implicit.THREE))
 (export "enum/Explicit.ZERO" (global $enum/Explicit.ZERO))
 (export "enum/Explicit.ONE" (global $enum/Explicit.ONE))
 (export "enum/Explicit.TWO" (global $enum/Explicit.TWO))
 (export "enum/Explicit.THREE" (global $enum/Explicit.THREE))
 (export "enum/Mixed.ZERO" (global $enum/Mixed.ZERO))
 (export "enum/Mixed.ONE" (global $enum/Mixed.ONE))
 (export "enum/Mixed.THREE" (global $enum/Mixed.THREE))
 (export "enum/Mixed.FOUR" (global $enum/Mixed.FOUR))
 (export "enum/SelfReference.ZERO" (global $enum/SelfReference.ZERO))
 (export "enum/SelfReference.ONE" (global $enum/SelfReference.ONE))
 (export "memory" (memory $0))
 (start $start)
 (func $enum/getZero (; 0 ;) (type $i) (result i32)
  ;;@ enum.ts:23:9
  (return
   (i32.const 0)
  )
 )
 (func $start (; 1 ;) (type $v)
  (set_global $enum/NonConstant.ZERO
   ;;@ enum.ts:27:9
   (call $enum/getZero)
  )
  (set_global $enum/NonConstant.ONE
   (i32.add
    (get_global $enum/NonConstant.ZERO)
    (i32.const 1)
   )
  )
 )
)
