(module
 (type $v (func))
 (memory $0 0)
 (export "foo" (func $inlining-recursive/foo))
 (export "baz" (func $inlining-recursive/baz))
 (export "bar" (func $inlining-recursive/bar))
 (export "memory" (memory $0))
 (func $inlining-recursive/foo (; 0 ;) (type $v)
  (call $inlining-recursive/foo)
 )
 (func $inlining-recursive/baz (; 1 ;) (type $v)
  (call $inlining-recursive/bar)
 )
 (func $inlining-recursive/bar (; 2 ;) (type $v)
  (call $inlining-recursive/baz)
 )
)
