(module
 (type $i (func (result i32)))
 (type $v (func))
 (memory $0 1)
 (export "test" (func $inlining/test))
 (export "memory" (memory $0))
 (start $start)
 (func $inlining/test (; 0 ;) (type $i) (result i32)
  (i32.const 3)
 )
 (func $start (; 1 ;) (type $v)
  ;;@ inlining.ts:8:0
  (nop)
 )
)
