(module
 (type $iii (func (param i32 i32) (result i32)))
 (type $v (func))
 (global $main/code (mut i32) (i32.const 0))
 (memory $0 1)
 (export "main" (func $main/main))
 (export "memory" (memory $0))
 (func $main/main (; 0 ;) (type $iii) (param $0 i32) (param $1 i32) (result i32)
  (call $start)
  (get_global $main/code)
 )
 (func $start (; 1 ;) (type $v)
  (set_global $main/code
   (i32.const 1)
  )
 )
)
