(module
 (type $i (func (result i32)))
 (type $v (func))
 (global $namespace/Outer.Inner.aVar (mut i32) (i32.const 0))
 (memory $0 1)
 (export "memory" (memory $0))
 (start $start)
 (func $namespace/Outer.Inner.aFunc (; 0 ;) (type $i) (result i32)
  (get_global $namespace/Outer.Inner.aVar)
 )
 (func $start (; 1 ;) (type $v)
  (drop
   (call $namespace/Outer.Inner.aFunc)
  )
 )
)
