(module
 (type $i (func (result i32)))
 (type $v (func))
 (global $namespace/Outer.Inner.aVar (mut i32) (i32.const 0))
 (global $namespace/Joined.THREE i32 (i32.const 3))
 (memory $0 1)
 (export "memory" (memory $0))
 (start $start)
 (func $start (; 0 ;) (type $v)
  (drop
   (block (result i32)
    (block $__inlined_func$namespace/Outer.Inner.aFunc (result i32)
     (get_global $namespace/Outer.Inner.aVar)
    )
   )
  )
  (drop
   (block (result i32)
    (block $__inlined_func$namespace/Joined.anotherFunc (result i32)
     (get_global $namespace/Joined.THREE)
    )
   )
  )
 )
)
