(module
 (type $v (func))
 (type $FUNCSIG$i (func (result i32)))
 (global $export/a i32 (i32.const 1))
 (global $export/b i32 (i32.const 2))
 (memory $0 0)
 (export "memory" (memory $0))
 (export "a" (global $export/a))
 (export "renamed_a" (global $export/a))
 (export "renamed_b" (global $export/b))
 (export "renamed_renamed_b" (global $export/b))
 (start $start)
 (func $export/add (; 0 ;) (; has Stack IR ;) (type $FUNCSIG$i) (result i32)
  (i32.const 3)
 )
 (func $export/mul (; 1 ;) (; has Stack IR ;) (type $FUNCSIG$i) (result i32)
  (i32.const 12)
 )
 (func $start (; 2 ;) (; has Stack IR ;) (type $v)
  (drop
   (i32.add
    (call $export/add)
    (call $export/mul)
   )
  )
 )
)
