(module
 (type $v (func))
 (global $ternary/a (mut i32) (i32.const 0))
 (global $HEAP_BASE i32 (i32.const 4))
 (memory $0 1)
 (export "memory" (memory $0))
 (start $start)
 (func $start (; 0 ;) (type $v)
  (if
   (i32.const 0)
   (unreachable)
   (drop
    (i32.const 1)
   )
  )
  (if
   (i32.const 1)
   (drop
    (i32.const 1)
   )
   (unreachable)
  )
  (if
   (if (result i32)
    (i32.const 0)
    (unreachable)
    (i32.const 1)
   )
   (drop
    (i32.const 1)
   )
   (unreachable)
  )
  (set_global $ternary/a
   (if (result i32)
    (i32.const 0)
    (unreachable)
    (i32.const 1)
   )
  )
  (set_global $ternary/a
   (if (result i32)
    (i32.const 1)
    (i32.const 1)
    (unreachable)
   )
  )
  (set_global $ternary/a
   (if (result i32)
    (if (result i32)
     (i32.const 0)
     (unreachable)
     (i32.const 1)
    )
    (i32.const 1)
    (unreachable)
   )
  )
 )
)
