(module
 (global $unicode-identifier/ÀÈ (mut i32) (i32.const 0))
 (global $unicode-identifier/变量 (mut i32) (i32.const 0))
 (global $unicode-identifier/𠜎𠜱 (mut i32) (i32.const 0))
 (global $~lib/memory/__data_end i32 (i32.const 8))
 (global $~lib/memory/__stack_pointer (mut i32) (i32.const 16392))
 (global $~lib/memory/__heap_base i32 (i32.const 16392))
 (memory $0 0)
 (table $0 1 1 funcref)
 (elem $0 (i32.const 1))
 (export "ÀÈ" (global $unicode-identifier/ÀÈ))
 (export "变量" (global $unicode-identifier/变量))
 (export "𠜎𠜱" (global $unicode-identifier/𠜎𠜱))
 (export "memory" (memory $0))
)
