(module
 (type $i (func (result i32)))
 (type $v (func))
 (memory $0 0)
 (export "memory" (memory $0))
 (start $start)
 (func $void/anInt (; 0 ;) (; has Stack IR ;) (type $i) (result i32)
  (i32.const 2)
 )
 (func $start (; 1 ;) (; has Stack IR ;) (type $v)
  (drop
   (call $void/anInt)
  )
 )
)
