[package]
name = "rust_nbody"
version = "0.1.0"
authors = ["MaxGraey <maxgraey@gmail.com>"]

[lib]
path       = "src/lib.rs"
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
