export declare function assert(value: externref): void;
export declare function clear(): void;
export declare function error(value: externref): void;
export declare function info(value: externref): void;
export declare function log(value: externref): void;
export declare function time(label: externref): externref;
export declare function timeEnd(label: externref): void;
export declare function timeLog(label: externref): void;
export declare function trace(): void;
export declare function warn(value: externref): void;
