name: assemblyscript
version: git
summary: A TypeScript-like language for WebAssembly.
description: |
  AssemblyScript compiles a variant of TypeScript to WebAssembly using Binaryen.

  See the AssemblyScript website for documentation:
  https://www.assemblyscript.org
icon: media/icon.svg
grade: stable
confinement: strict
apps:
  asc:
    command: asc
  asinit:
    command: asinit
parts:
  assemblyscript:
    source: .
    plugin: npm
    npm-node-version: 16.9.1
architectures: 
  - build-on: amd64 
    run-on: [amd64, armhf, arm64, i386]
