name: assemblyscript
version: git
summary: A TypeScript-like language for WebAssembly.
description: |
  AssemblyScript compiles a variant of TypeScript to WebAssembly using Binaryen.

  See the AssemblyScript website for documentation:
  https://www.assemblyscript.org
base: core20
icon: media/icon.svg
grade: stable
confinement: strict
apps:
  asc:
    command: bin/asc
  asinit:
    command: bin/asinit
parts:
  assemblyscript:
    plugin: nodejs
    nodejs-version: 16.13.1
    nodejs-package-manager: npm
    source: .
    override-build: |
      npm install
      npm run build
      node ./scripts/prepublish
      npm prune
architectures:
  - build-on: amd64
    run-on: [amd64, armhf, arm64, i386]
