name: DistCheck
on:
  pull_request:
    paths:
    - 'dist/*'
jobs:
  check:
    name: 'Fail on dist file changes'
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Distribution files must not be modified."
        exit 1
