name: CI
on: [push, pull_request]

jobs:
  test:
    name: "Test on node: ${{ matrix.node_version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["lts/*", "node"]
    steps:
    - uses: actions/checkout@master
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: npm ci --no-audit
    - name: Clean
      run: npm run clean
    - name: Test sources
      run: npm test
    - name: Build
      run: npm run build
    - name: Test distribution
      run: npm test
  test-canary:
    name: "Test on node: canary"
    runs-on: ubuntu-latest
    env:
      ASC_FEATURES: mutable-globals,simd,threads,reference-types,bigint-integration
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: node
        node-mirror: https://nodejs.org/download/v8-canary/
    - name: Install dependencies
      run: npm ci --no-audit
    - name: Clean
      run: npm run clean
    - name: Test experimental features
      run: "npm run test:compiler rt/flags features/js-bigint-integration features/reference-types features/simd features/threads"
