name: CI
on: [push, pull_request]

jobs:
  test:
    name: "Test on node: ${{ matrix.node_version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["lts/*", "node"]
    steps:
    - uses: actions/checkout@master
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node_version: ${{ matrix.node_version }}
    - name: Do it
      run: |
        which node
        node -v
        which npm
        npm -v
        npm ci --no-audit
        npm run clean
        npm test
        npm run build
        npm test
  test-canary:
    name: "Test on node: canary"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Do it
      env:
        NVM_NODEJS_ORG_MIRROR: https://nodejs.org/download/v8-canary/
        ASC_FEATURES: mutable-globals,simd,threads,reference-types,bigint-integration
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        chmod +x $NVM_DIR/nvm.sh
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install node
        nvm use node
        which node
        node -v
        npm -g install npm
        which npm
        npm -v
        npm ci --no-audit
        npm run clean
        npm run test:compiler rt/flags features/js-bigint-integration features/reference-types features/simd features/threads
