name: PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Prefix
        id: title-check
        uses: actions/github-script@v7
        with:
          script: |
            const titlePrefixes = ["feat", "fix", "breaking", "chore"];
            const title = context.payload.pull_request.title.toLowerCase();
            const titleHasValidPrefix = titlePrefixes.some((prefix) => title.startsWith(`${prefix}:`));
            if (!titleHasValidPrefix) { process.exit(-1); }
