name: PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Prefix
        id: title-check
        uses: actions/github-script@v9
        with:
          script: |
            const prefs = ["feat", "fix", "breaking", "chore"];
            const title = context.payload.pull_request.title.toLowerCase();
            const hasValidPrefix = prefs.some(prefix => title.startsWith(`${prefix}:`));
            if (!hasValidPrefix)
              core.setFailed("PR title must start with 'feat:', 'fix:', 'breaking:' or 'chore:'");
